runtime: python39

# Environment variables for production
env_variables:
  FLASK_ENV: production
  SECRET_KEY: "your-super-secure-secret-key-change-this-in-production"
  GAE_ENV: standard

# Instance configuration
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  cool_down_period: 120s
  target_cpu_utilization: 0.6

# URL handlers
handlers:
# Static files (CSS, JS, images)
- url: /static
  static_dir: static
  secure: always

# Favicon
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

# All other URLs go to the Flask app
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

# Skip files that shouldn't be uploaded to App Engine
skip_files:
- .git/
- .gitignore
- .venv/
- __pycache__/
- *.pyc
- .pytest_cache/
- verify_account_info_removal.py
- check_page_content.py
- test_*.py
- debug_routes.py
- setup_database.py
- migrate_*.py
- demo_*.py
- *.md
- README.md
