name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker
        run: | 
          gcloud auth configure-docker -q

      - name: Build and push image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/app-laundry:${{ github.sha }}
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/app-laundry:${{ github.sha }}
          gcloud run deploy app-laundry --image "$IMAGE" --region ${{ secrets.GCP_REGION }} --platform managed --allow-unauthenticated --set-env-vars PORT=8080

# Required repository secrets:
# - GCP_SA_KEY: JSON service account key for a service account with Cloud Run deploy permissions
# - GCP_PROJECT: GCP project id
# - GCP_REGION: region for Cloud Run (e.g., us-central1)