name: Dockerfile Lint

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-lint.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Lint Dockerfile with hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
